version: "3.7"
services:
  database:
    image: mysql
    container_name: db
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    expose:
      - "3306"